### ISSUE TITLE
Get tokens with setup_oauth2.rb

### ISSUE THREAD

**Issue by grishkovelli** [googleads/google-api-ads-ruby#111]
Hi. I was trying to get tokens but I couldn't. I don't know what is wrong with it, because it worked before.

**adwords_api.yml**
```
authentication:
  method: OAuth2
  oauth2_client_id: VALUE
  oauth2_client_secret: VALUE
  developer_token: VALUE
  client_customer_id: VALUE
  user_agent: firefox
```

**Error**
```
~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-ads-common-0.12.5/lib/ads_common/credential_handler.rb:37:in `dup': can't dup NilClass (TypeError)
~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-ads-common-0.12.5/lib/ads_common/credential_handler.rb:37:in `credentials'
	from ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-adwords-api-0.22.0/lib/adwords_api/credential_handler.rb:39:in `credentials'
```
